// Package migrate converts Claude Code settings.json permissions to gatekeeper TOML.
package migrate

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// Settings represents the relevant portion of Claude Code settings.json.
type Settings struct {
	Permissions *Permissions `json:"permissions"`
}

// Permissions holds allow/deny glob arrays.
type Permissions struct {
	Allow []string `json:"allow"`
	Deny  []string `json:"deny"`
}

// parsedGlob is a decomposed permission glob like Bash(git add:*).
type parsedGlob struct {
	Tool    string
	Pattern string
}

var globRe = regexp.MustCompile(`^(\w+)\((.+)\)$`)

// Run executes the migration from settings.json to gatekeeper TOML.
func Run(settingsPath, outputPath string) error {
	if settingsPath == "" {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot determine home directory: %w", err)
		}
		settingsPath = filepath.Join(homeDir, ".claude", "settings.json")
	}

	localPath := strings.TrimSuffix(settingsPath, ".json") + ".local.json"

	fmt.Fprintf(os.Stderr, "Reading: %s\n", settingsPath)
	mainSettings, mainErr := readSettings(settingsPath)

	fmt.Fprintf(os.Stderr, "Reading: %s\n", localPath)
	localSettings, localErr := readSettings(localPath)

	if mainErr != nil && localErr != nil {
		return fmt.Errorf("could not read any settings file:\n  %s: %v\n  %s: %v",
			settingsPath, mainErr, localPath, localErr)
	}

	var allowGlobs, denyGlobs []string
	if mainErr == nil && mainSettings.Permissions != nil {
		allowGlobs = append(allowGlobs, mainSettings.Permissions.Allow...)
		denyGlobs = append(denyGlobs, mainSettings.Permissions.Deny...)
	}
	if localErr == nil && localSettings.Permissions != nil {
		allowGlobs = append(allowGlobs, localSettings.Permissions.Allow...)
		denyGlobs = append(denyGlobs, localSettings.Permissions.Deny...)
	}

	if len(allowGlobs) == 0 && len(denyGlobs) == 0 {
		fmt.Fprintf(os.Stderr, "No permission rules found in settings files.\n")
		return nil
	}

	tomlContent := generateTOML(allowGlobs, denyGlobs)

	if outputPath == "" {
		homeDir, _ := os.UserHomeDir()
		outputPath = filepath.Join(homeDir, ".claude", ".gatekeeper.toml")
	}

	// Create backup if target exists.
	if _, err := os.Stat(outputPath); err == nil {
		backupPath := outputPath + ".backup." + time.Now().Format("20060102-150405")
		if err := copyFile(outputPath, backupPath); err != nil {
			return fmt.Errorf("creating backup: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Backup: %s\n", backupPath)
	}

	if err := os.WriteFile(outputPath, []byte(tomlContent), 0644); err != nil {
		return fmt.Errorf("writing output: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Wrote:   %s\n", outputPath)
	fmt.Fprintf(os.Stderr, "\n")
	fmt.Fprintf(os.Stderr, "=== Next steps ===\n")
	fmt.Fprintf(os.Stderr, "1. Review the generated TOML and fix any # TODO lines.\n")
	fmt.Fprintf(os.Stderr, "2. Optionally refine with:\n")
	fmt.Fprintf(os.Stderr, "     claude -p \"Convert these Claude Code permission globs to\n")
	fmt.Fprintf(os.Stderr, "     PCRE2-compatible regex for claude-gatekeeper. Here are the\n")
	allGlobs := make([]string, 0, len(allowGlobs)+len(denyGlobs))
	allGlobs = append(allGlobs, allowGlobs...)
	allGlobs = append(allGlobs, denyGlobs...)
	fmt.Fprintf(os.Stderr, "     original globs:\\n%s\"\n", strings.Join(allGlobs, "\\n"))
	fmt.Fprintf(os.Stderr, "3. Remove the 'permissions' block from your settings.json files.\n")
	fmt.Fprintf(os.Stderr, "4. Install the hook:  make install\n")
	return nil
}

func readSettings(path string) (*Settings, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var s Settings
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

func generateTOML(allowGlobs, denyGlobs []string) string {
	var b strings.Builder
	b.WriteString("# Claude Gatekeeper — Migrated from settings.json\n")
	b.WriteString("#\n")
	b.WriteString("# Generated by: claude-gatekeeper migrate\n")
	b.WriteString("# Review each rule and adjust the regex as needed.\n")
	b.WriteString("#\n")
	b.WriteString("# Set to false to disable the built-in default rules:\n")
	b.WriteString("# include_defaults = false\n\n")

	if len(denyGlobs) > 0 {
		b.WriteString("# === DENY rules (migrated) ===\n\n")
		for _, g := range denyGlobs {
			writeRule(&b, g, "deny")
		}
	}

	if len(allowGlobs) > 0 {
		b.WriteString("# === ALLOW rules (migrated) ===\n\n")
		for _, g := range allowGlobs {
			writeRule(&b, g, "allow")
		}
	}

	return b.String()
}

func writeRule(b *strings.Builder, glob, decision string) {
	parsed := parseGlob(glob)
	regex := globToRegex(parsed.Pattern)

	b.WriteString(fmt.Sprintf("# Original: %s\n", glob))
	if strings.Contains(regex, "TODO") {
		b.WriteString("# TODO: Review this conversion — the glob may not map cleanly to regex.\n")
	}
	b.WriteString("[[rules]]\n")
	b.WriteString(fmt.Sprintf("tool     = '%s'\n", parsed.Tool))
	b.WriteString(fmt.Sprintf("input    = '%s'\n", regex))
	b.WriteString(fmt.Sprintf("decision = \"%s\"\n", decision))
	b.WriteString(fmt.Sprintf("reason   = \"Migrated from: %s\"\n\n", glob))
}

func parseGlob(glob string) parsedGlob {
	m := globRe.FindStringSubmatch(glob)
	if m != nil {
		return parsedGlob{Tool: m[1], Pattern: m[2]}
	}
	// No parens: treat as a tool name match for everything.
	return parsedGlob{Tool: glob, Pattern: "*"}
}

// globToRegex does a best-effort conversion of a Claude Code permission glob to regex.
func globToRegex(pattern string) string {
	// Handle the common "prefix:*" pattern.
	if strings.HasSuffix(pattern, ":*") {
		prefix := strings.TrimSuffix(pattern, ":*")
		// Escape regex-special chars in the prefix, then allow anything after.
		escaped := regexEscape(prefix)
		return "^" + escaped + "\\b"
	}

	// Handle bare "*" (match anything).
	if pattern == "*" {
		return ".*"
	}

	// General glob-to-regex: escape everything, then convert * and ?.
	escaped := regexEscape(pattern)
	escaped = strings.ReplaceAll(escaped, `\*`, ".*")
	escaped = strings.ReplaceAll(escaped, `\?`, ".")
	return escaped + " # TODO: verify conversion"
}

func regexEscape(s string) string {
	special := `\.+*?^${}()|[]`
	var b strings.Builder
	for _, c := range s {
		if strings.ContainsRune(special, c) {
			b.WriteRune('\\')
		}
		b.WriteRune(c)
	}
	return b.String()
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0644)
}
